name: Test matrix

on:
  push:
  workflow_dispatch:
    inputs:
      weaviate_version:
        description: 'Weaviate version to test'
        required: false

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  run-with-sync-indexing:
    strategy:
      fail-fast: false
      matrix:
        lsm_access_strategy: ["mmap", "pread"]
    uses: ./.github/workflows/tests.yaml
    with:
      lsm_access_strategy: ${{matrix.lsm_access_strategy}}
      weaviate_version: ${{ github.event.inputs.weaviate_version || '' }}
    secrets:
      AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      GCP_SERVICE_ACCOUNT_BENCHMARKS: ${{secrets.GCP_SERVICE_ACCOUNT_BENCHMARKS}}
      POLARSIGNALS_TOKEN: ${{secrets.POLARSIGNALS_TOKEN}}
